--
-- PostgreSQL database dump
--

\restrict p3uPbWa9swtg9ugQW7AmtyEAavBcX1xWeg7nwJEBdpldn1NnudCOya58Sh8tSAW

-- Dumped from database version 16.12 (Debian 16.12-1.pgdg13+1)
-- Dumped by pg_dump version 16.12 (Debian 16.12-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: caja; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.caja (
    id_caja integer NOT NULL,
    estado character varying(50),
    fecha_apertura timestamp(6) without time zone,
    fecha_cierre timestamp(6) without time zone,
    monto_final numeric(12,2),
    monto_inicial numeric(12,2),
    id_empleado bigint
);


ALTER TABLE public.caja OWNER TO posuser;

--
-- Name: caja_id_caja_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.caja ALTER COLUMN id_caja ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.caja_id_caja_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categoria_producto; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.categoria_producto (
    id_categoria bigint NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.categoria_producto OWNER TO posuser;

--
-- Name: categoria_producto_id_categoria_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.categoria_producto ALTER COLUMN id_categoria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categoria_producto_id_categoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ciudad; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.ciudad (
    id_ciudad bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    id_pais bigint
);


ALTER TABLE public.ciudad OWNER TO posuser;

--
-- Name: ciudad_id_ciudad_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.ciudad ALTER COLUMN id_ciudad ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ciudad_id_ciudad_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cliente; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.cliente (
    id_cliente bigint NOT NULL,
    date_birth date,
    document_number character varying(255),
    document_type character varying(255),
    first_name character varying(255),
    gender character varying(255),
    last_name character varying(255),
    apellido character varying(100),
    documento character varying(20),
    nombre character varying(100),
    telefono character varying(30),
    nationality_id_pais bigint,
    id_ciudad bigint
);


ALTER TABLE public.cliente OWNER TO posuser;

--
-- Name: cliente_id_cliente_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.cliente ALTER COLUMN id_cliente ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cliente_id_cliente_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contacto_cliente; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.contacto_cliente (
    id_contacto_cliente bigint NOT NULL,
    email character varying(100),
    nombre_contacto character varying(100),
    telefono character varying(50),
    id_cliente bigint
);


ALTER TABLE public.contacto_cliente OWNER TO posuser;

--
-- Name: contacto_cliente_id_contacto_cliente_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.contacto_cliente ALTER COLUMN id_contacto_cliente ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contacto_cliente_id_contacto_cliente_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contacto_proveedor; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.contacto_proveedor (
    id_contacto_proveedor bigint NOT NULL,
    email character varying(100),
    nombre_contacto character varying(100),
    telefono character varying(50),
    id_proveedor bigint
);


ALTER TABLE public.contacto_proveedor OWNER TO posuser;

--
-- Name: contacto_proveedor_id_contacto_proveedor_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.contacto_proveedor ALTER COLUMN id_contacto_proveedor ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contacto_proveedor_id_contacto_proveedor_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: detalle_factura; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.detalle_factura (
    id_detalle_factura bigint NOT NULL,
    cantidad numeric(10,2),
    precio_unitario numeric(10,2),
    id_factura bigint,
    id_producto bigint
);


ALTER TABLE public.detalle_factura OWNER TO posuser;

--
-- Name: detalle_factura_compra; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.detalle_factura_compra (
    id_detalle_factura_compra bigint NOT NULL,
    cantidad numeric(10,2),
    precio_unitario numeric(10,2),
    id_factura_compra bigint,
    id_producto bigint
);


ALTER TABLE public.detalle_factura_compra OWNER TO posuser;

--
-- Name: detalle_factura_compra_id_detalle_factura_compra_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.detalle_factura_compra ALTER COLUMN id_detalle_factura_compra ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_factura_compra_id_detalle_factura_compra_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: detalle_factura_id_detalle_factura_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.detalle_factura ALTER COLUMN id_detalle_factura ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_factura_id_detalle_factura_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: detalle_inventario; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.detalle_inventario (
    id_detalle_inventario bigint NOT NULL,
    cantidad_fisica numeric(10,2),
    cantidad_sistema numeric(10,2),
    diferencia numeric(10,2),
    id_inventario bigint,
    id_producto bigint
);


ALTER TABLE public.detalle_inventario OWNER TO posuser;

--
-- Name: detalle_inventario_id_detalle_inventario_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.detalle_inventario ALTER COLUMN id_detalle_inventario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_inventario_id_detalle_inventario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: detalle_orden_compra; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.detalle_orden_compra (
    id_detalle_orden_compra bigint NOT NULL,
    cantidad numeric(38,2) NOT NULL,
    precio_unitario numeric(38,2) NOT NULL,
    id_orden_compra bigint NOT NULL,
    id_producto bigint NOT NULL
);


ALTER TABLE public.detalle_orden_compra OWNER TO posuser;

--
-- Name: detalle_orden_compra_id_detalle_orden_compra_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.detalle_orden_compra ALTER COLUMN id_detalle_orden_compra ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_orden_compra_id_detalle_orden_compra_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: detalle_pedido; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.detalle_pedido (
    id_detalle_pedido bigint NOT NULL,
    cantidad numeric(10,2),
    precio_unitario numeric(10,2),
    id_pedido bigint,
    id_producto bigint
);


ALTER TABLE public.detalle_pedido OWNER TO posuser;

--
-- Name: detalle_pedido_id_detalle_pedido_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.detalle_pedido ALTER COLUMN id_detalle_pedido ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_pedido_id_detalle_pedido_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: empleado; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.empleado (
    id_empleado bigint NOT NULL,
    apellido character varying(100),
    documento character varying(20),
    nombre character varying(100) NOT NULL,
    telefono character varying(30),
    id_ciudad bigint,
    id_rol bigint
);


ALTER TABLE public.empleado OWNER TO posuser;

--
-- Name: empleado_id_empleado_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.empleado ALTER COLUMN id_empleado ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.empleado_id_empleado_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: factura; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.factura (
    id_factura bigint NOT NULL,
    fecha timestamp(6) without time zone,
    nro_factura character varying(50),
    total numeric(12,2),
    id_cliente bigint,
    id_pedido bigint
);


ALTER TABLE public.factura OWNER TO posuser;

--
-- Name: factura_compra; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.factura_compra (
    id_factura_compra bigint NOT NULL,
    fecha timestamp(6) without time zone,
    total numeric(12,2),
    id_proveedor bigint
);


ALTER TABLE public.factura_compra OWNER TO posuser;

--
-- Name: factura_compra_id_factura_compra_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.factura_compra ALTER COLUMN id_factura_compra ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.factura_compra_id_factura_compra_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: factura_id_factura_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.factura ALTER COLUMN id_factura ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.factura_id_factura_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forma_pago; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.forma_pago (
    id_forma_pago bigint NOT NULL,
    descripcion character varying(100)
);


ALTER TABLE public.forma_pago OWNER TO posuser;

--
-- Name: forma_pago_id_forma_pago_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.forma_pago ALTER COLUMN id_forma_pago ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forma_pago_id_forma_pago_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: historial_precio_producto; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.historial_precio_producto (
    id_historial_precio_producto bigint NOT NULL,
    fecha_cambio timestamp(6) without time zone NOT NULL,
    precio_anterior numeric(10,2),
    precio_nuevo numeric(10,2) NOT NULL,
    usuario_responsable character varying(100),
    id_producto bigint NOT NULL
);


ALTER TABLE public.historial_precio_producto OWNER TO posuser;

--
-- Name: historial_precio_producto_id_historial_precio_producto_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.historial_precio_producto ALTER COLUMN id_historial_precio_producto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.historial_precio_producto_id_historial_precio_producto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventario; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.inventario (
    id_inventario bigint NOT NULL,
    ajuste_realizado boolean,
    fecha date NOT NULL,
    observaciones text,
    id_empleado bigint
);


ALTER TABLE public.inventario OWNER TO posuser;

--
-- Name: inventario_id_inventario_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.inventario ALTER COLUMN id_inventario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventario_id_inventario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movimiento_caja; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.movimiento_caja (
    id_mov_caja bigint NOT NULL,
    fecha timestamp(6) without time zone,
    monto numeric(12,2),
    motivo text,
    id_caja integer,
    id_tipo_mov_caja bigint
);


ALTER TABLE public.movimiento_caja OWNER TO posuser;

--
-- Name: movimiento_caja_id_mov_caja_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.movimiento_caja ALTER COLUMN id_mov_caja ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimiento_caja_id_mov_caja_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movimiento_inventario; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.movimiento_inventario (
    id_movimiento bigint NOT NULL,
    cantidad numeric(10,2),
    fecha timestamp(6) without time zone,
    referencia text,
    id_producto bigint,
    id_tipo_movimiento bigint
);


ALTER TABLE public.movimiento_inventario OWNER TO posuser;

--
-- Name: movimiento_inventario_id_movimiento_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.movimiento_inventario ALTER COLUMN id_movimiento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimiento_inventario_id_movimiento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orden_compra; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.orden_compra (
    id_orden_compra bigint NOT NULL,
    estado character varying(50) NOT NULL,
    fecha_emision date NOT NULL,
    observaciones text,
    id_empleado bigint NOT NULL,
    id_proveedor bigint NOT NULL
);


ALTER TABLE public.orden_compra OWNER TO posuser;

--
-- Name: orden_compra_id_orden_compra_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.orden_compra ALTER COLUMN id_orden_compra ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orden_compra_id_orden_compra_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pago_proveedor; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.pago_proveedor (
    id_pago bigint NOT NULL,
    descripcion text,
    fecha timestamp(6) without time zone,
    monto numeric(12,2),
    id_proveedor bigint
);


ALTER TABLE public.pago_proveedor OWNER TO posuser;

--
-- Name: pago_proveedor_id_pago_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.pago_proveedor ALTER COLUMN id_pago ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pago_proveedor_id_pago_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pais; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.pais (
    id_pais bigint NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.pais OWNER TO posuser;

--
-- Name: pais_id_pais_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.pais ALTER COLUMN id_pais ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pais_id_pais_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pedido; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.pedido (
    id_pedido bigint NOT NULL,
    fecha timestamp(6) without time zone,
    total numeric(12,2),
    id_cliente bigint,
    id_empleado bigint
);


ALTER TABLE public.pedido OWNER TO posuser;

--
-- Name: pedido_id_pedido_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.pedido ALTER COLUMN id_pedido ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedido_id_pedido_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permiso; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.permiso (
    id_permiso bigint NOT NULL,
    descripcion text,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.permiso OWNER TO posuser;

--
-- Name: permiso_id_permiso_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.permiso ALTER COLUMN id_permiso ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permiso_id_permiso_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: producto; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.producto (
    id_producto bigint NOT NULL,
    codigo_producto character varying(20) NOT NULL,
    stock_actual numeric(10,2),
    descripcion text,
    nombre character varying(150) NOT NULL,
    precio numeric(10,2) NOT NULL,
    id_categoria bigint,
    id_proveedor bigint,
    id_unidad bigint
);


ALTER TABLE public.producto OWNER TO posuser;

--
-- Name: producto_id_producto_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.producto ALTER COLUMN id_producto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_id_producto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: proveedor; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.proveedor (
    id_proveedor bigint NOT NULL,
    nombre character varying(150) NOT NULL
);


ALTER TABLE public.proveedor OWNER TO posuser;

--
-- Name: proveedor_id_proveedor_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.proveedor ALTER COLUMN id_proveedor ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proveedor_id_proveedor_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rol; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.rol (
    id_rol bigint NOT NULL,
    nombre character varying(50) NOT NULL
);


ALTER TABLE public.rol OWNER TO posuser;

--
-- Name: rol_empleado; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.rol_empleado (
    id_rol bigint NOT NULL,
    descripcion text,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.rol_empleado OWNER TO posuser;

--
-- Name: rol_empleado_id_rol_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.rol_empleado ALTER COLUMN id_rol ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rol_empleado_id_rol_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rol_id_rol_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.rol ALTER COLUMN id_rol ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rol_id_rol_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rol_permiso; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.rol_permiso (
    id_rol bigint NOT NULL,
    id_permiso bigint
);


ALTER TABLE public.rol_permiso OWNER TO posuser;

--
-- Name: rol_permiso_id_rol_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.rol_permiso ALTER COLUMN id_rol ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rol_permiso_id_rol_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subcategoria_producto; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.subcategoria_producto (
    id_subcategoria bigint NOT NULL,
    descripcion character varying(255),
    nombre character varying(100) NOT NULL,
    id_categoria bigint NOT NULL
);


ALTER TABLE public.subcategoria_producto OWNER TO posuser;

--
-- Name: subcategoria_producto_id_subcategoria_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.subcategoria_producto ALTER COLUMN id_subcategoria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subcategoria_producto_id_subcategoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipo_movimiento; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.tipo_movimiento (
    id_tipo_movimiento bigint NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.tipo_movimiento OWNER TO posuser;

--
-- Name: tipo_movimiento_caja; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.tipo_movimiento_caja (
    id_tipo_mov_caja bigint NOT NULL,
    nombre character varying(100)
);


ALTER TABLE public.tipo_movimiento_caja OWNER TO posuser;

--
-- Name: tipo_movimiento_caja_id_tipo_mov_caja_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.tipo_movimiento_caja ALTER COLUMN id_tipo_mov_caja ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipo_movimiento_caja_id_tipo_mov_caja_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipo_movimiento_id_tipo_movimiento_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.tipo_movimiento ALTER COLUMN id_tipo_movimiento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tipo_movimiento_id_tipo_movimiento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transferencia_informacion; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.transferencia_informacion (
    id_transferencia bigint NOT NULL,
    descripcion text,
    destino character varying(100),
    fecha timestamp(6) without time zone,
    origen character varying(100)
);


ALTER TABLE public.transferencia_informacion OWNER TO posuser;

--
-- Name: transferencia_informacion_id_transferencia_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.transferencia_informacion ALTER COLUMN id_transferencia ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transferencia_informacion_id_transferencia_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: turno; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.turno (
    id_turno bigint NOT NULL,
    descripcion character varying(100),
    hora_fin time(0) without time zone,
    hora_inicio time(0) without time zone,
    id_empleado bigint
);


ALTER TABLE public.turno OWNER TO posuser;

--
-- Name: turno_id_turno_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.turno ALTER COLUMN id_turno ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.turno_id_turno_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: unidad_medida; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.unidad_medida (
    id_unidad bigint NOT NULL,
    abreviatura character varying(10),
    nombre character varying(50) NOT NULL
);


ALTER TABLE public.unidad_medida OWNER TO posuser;

--
-- Name: unidad_medida_id_unidad_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.unidad_medida ALTER COLUMN id_unidad ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.unidad_medida_id_unidad_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.usuario (
    id_usuario bigint NOT NULL,
    activo boolean NOT NULL,
    nombre character varying(100),
    password_hash text NOT NULL,
    username character varying(50) NOT NULL
);


ALTER TABLE public.usuario OWNER TO posuser;

--
-- Name: usuario_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.usuario ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario_rol; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.usuario_rol (
    id_usuario bigint NOT NULL,
    id_rol bigint NOT NULL
);


ALTER TABLE public.usuario_rol OWNER TO posuser;

--
-- Data for Name: caja; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.caja (id_caja, estado, fecha_apertura, fecha_cierre, monto_final, monto_inicial, id_empleado) FROM stdin;
\.


--
-- Data for Name: categoria_producto; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.categoria_producto (id_categoria, nombre) FROM stdin;
1	Comestibles
\.


--
-- Data for Name: ciudad; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.ciudad (id_ciudad, nombre, id_pais) FROM stdin;
\.


--
-- Data for Name: cliente; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.cliente (id_cliente, date_birth, document_number, document_type, first_name, gender, last_name, apellido, documento, nombre, telefono, nationality_id_pais, id_ciudad) FROM stdin;
\.


--
-- Data for Name: contacto_cliente; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.contacto_cliente (id_contacto_cliente, email, nombre_contacto, telefono, id_cliente) FROM stdin;
\.


--
-- Data for Name: contacto_proveedor; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.contacto_proveedor (id_contacto_proveedor, email, nombre_contacto, telefono, id_proveedor) FROM stdin;
\.


--
-- Data for Name: detalle_factura; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.detalle_factura (id_detalle_factura, cantidad, precio_unitario, id_factura, id_producto) FROM stdin;
\.


--
-- Data for Name: detalle_factura_compra; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.detalle_factura_compra (id_detalle_factura_compra, cantidad, precio_unitario, id_factura_compra, id_producto) FROM stdin;
\.


--
-- Data for Name: detalle_inventario; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.detalle_inventario (id_detalle_inventario, cantidad_fisica, cantidad_sistema, diferencia, id_inventario, id_producto) FROM stdin;
\.


--
-- Data for Name: detalle_orden_compra; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.detalle_orden_compra (id_detalle_orden_compra, cantidad, precio_unitario, id_orden_compra, id_producto) FROM stdin;
\.


--
-- Data for Name: detalle_pedido; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.detalle_pedido (id_detalle_pedido, cantidad, precio_unitario, id_pedido, id_producto) FROM stdin;
\.


--
-- Data for Name: empleado; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.empleado (id_empleado, apellido, documento, nombre, telefono, id_ciudad, id_rol) FROM stdin;
\.


--
-- Data for Name: factura; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.factura (id_factura, fecha, nro_factura, total, id_cliente, id_pedido) FROM stdin;
\.


--
-- Data for Name: factura_compra; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.factura_compra (id_factura_compra, fecha, total, id_proveedor) FROM stdin;
\.


--
-- Data for Name: forma_pago; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.forma_pago (id_forma_pago, descripcion) FROM stdin;
\.


--
-- Data for Name: historial_precio_producto; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.historial_precio_producto (id_historial_precio_producto, fecha_cambio, precio_anterior, precio_nuevo, usuario_responsable, id_producto) FROM stdin;
\.


--
-- Data for Name: inventario; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.inventario (id_inventario, ajuste_realizado, fecha, observaciones, id_empleado) FROM stdin;
\.


--
-- Data for Name: movimiento_caja; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.movimiento_caja (id_mov_caja, fecha, monto, motivo, id_caja, id_tipo_mov_caja) FROM stdin;
\.


--
-- Data for Name: movimiento_inventario; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.movimiento_inventario (id_movimiento, cantidad, fecha, referencia, id_producto, id_tipo_movimiento) FROM stdin;
\.


--
-- Data for Name: orden_compra; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.orden_compra (id_orden_compra, estado, fecha_emision, observaciones, id_empleado, id_proveedor) FROM stdin;
\.


--
-- Data for Name: pago_proveedor; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.pago_proveedor (id_pago, descripcion, fecha, monto, id_proveedor) FROM stdin;
\.


--
-- Data for Name: pais; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.pais (id_pais, nombre) FROM stdin;
\.


--
-- Data for Name: pedido; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.pedido (id_pedido, fecha, total, id_cliente, id_empleado) FROM stdin;
\.


--
-- Data for Name: permiso; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.permiso (id_permiso, descripcion, nombre) FROM stdin;
\.


--
-- Data for Name: producto; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.producto (id_producto, codigo_producto, stock_actual, descripcion, nombre, precio, id_categoria, id_proveedor, id_unidad) FROM stdin;
2	78412789561312	12.00	Papas fritas 125gr	Lays	12000.00	1	1	1
\.


--
-- Data for Name: proveedor; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.proveedor (id_proveedor, nombre) FROM stdin;
1	Conti
\.


--
-- Data for Name: rol; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.rol (id_rol, nombre) FROM stdin;
\.


--
-- Data for Name: rol_empleado; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.rol_empleado (id_rol, descripcion, nombre) FROM stdin;
\.


--
-- Data for Name: rol_permiso; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.rol_permiso (id_rol, id_permiso) FROM stdin;
\.


--
-- Data for Name: subcategoria_producto; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.subcategoria_producto (id_subcategoria, descripcion, nombre, id_categoria) FROM stdin;
\.


--
-- Data for Name: tipo_movimiento; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.tipo_movimiento (id_tipo_movimiento, nombre) FROM stdin;
\.


--
-- Data for Name: tipo_movimiento_caja; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.tipo_movimiento_caja (id_tipo_mov_caja, nombre) FROM stdin;
\.


--
-- Data for Name: transferencia_informacion; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.transferencia_informacion (id_transferencia, descripcion, destino, fecha, origen) FROM stdin;
\.


--
-- Data for Name: turno; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.turno (id_turno, descripcion, hora_fin, hora_inicio, id_empleado) FROM stdin;
\.


--
-- Data for Name: unidad_medida; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.unidad_medida (id_unidad, abreviatura, nombre) FROM stdin;
1	gr	Gramos
\.


--
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.usuario (id_usuario, activo, nombre, password_hash, username) FROM stdin;
\.


--
-- Data for Name: usuario_rol; Type: TABLE DATA; Schema: public; Owner: posuser
--

COPY public.usuario_rol (id_usuario, id_rol) FROM stdin;
\.


--
-- Name: caja_id_caja_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.caja_id_caja_seq', 1, false);


--
-- Name: categoria_producto_id_categoria_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.categoria_producto_id_categoria_seq', 1, true);


--
-- Name: ciudad_id_ciudad_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.ciudad_id_ciudad_seq', 1, false);


--
-- Name: cliente_id_cliente_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.cliente_id_cliente_seq', 1, false);


--
-- Name: contacto_cliente_id_contacto_cliente_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.contacto_cliente_id_contacto_cliente_seq', 1, false);


--
-- Name: contacto_proveedor_id_contacto_proveedor_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.contacto_proveedor_id_contacto_proveedor_seq', 1, false);


--
-- Name: detalle_factura_compra_id_detalle_factura_compra_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.detalle_factura_compra_id_detalle_factura_compra_seq', 1, false);


--
-- Name: detalle_factura_id_detalle_factura_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.detalle_factura_id_detalle_factura_seq', 1, false);


--
-- Name: detalle_inventario_id_detalle_inventario_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.detalle_inventario_id_detalle_inventario_seq', 1, false);


--
-- Name: detalle_orden_compra_id_detalle_orden_compra_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.detalle_orden_compra_id_detalle_orden_compra_seq', 1, false);


--
-- Name: detalle_pedido_id_detalle_pedido_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.detalle_pedido_id_detalle_pedido_seq', 1, false);


--
-- Name: empleado_id_empleado_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.empleado_id_empleado_seq', 1, false);


--
-- Name: factura_compra_id_factura_compra_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.factura_compra_id_factura_compra_seq', 1, false);


--
-- Name: factura_id_factura_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.factura_id_factura_seq', 1, false);


--
-- Name: forma_pago_id_forma_pago_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.forma_pago_id_forma_pago_seq', 1, false);


--
-- Name: historial_precio_producto_id_historial_precio_producto_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.historial_precio_producto_id_historial_precio_producto_seq', 1, false);


--
-- Name: inventario_id_inventario_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.inventario_id_inventario_seq', 1, false);


--
-- Name: movimiento_caja_id_mov_caja_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.movimiento_caja_id_mov_caja_seq', 1, false);


--
-- Name: movimiento_inventario_id_movimiento_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.movimiento_inventario_id_movimiento_seq', 1, false);


--
-- Name: orden_compra_id_orden_compra_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.orden_compra_id_orden_compra_seq', 1, false);


--
-- Name: pago_proveedor_id_pago_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.pago_proveedor_id_pago_seq', 1, false);


--
-- Name: pais_id_pais_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.pais_id_pais_seq', 1, false);


--
-- Name: pedido_id_pedido_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.pedido_id_pedido_seq', 1, false);


--
-- Name: permiso_id_permiso_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.permiso_id_permiso_seq', 1, false);


--
-- Name: producto_id_producto_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.producto_id_producto_seq', 2, true);


--
-- Name: proveedor_id_proveedor_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.proveedor_id_proveedor_seq', 1, true);


--
-- Name: rol_empleado_id_rol_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.rol_empleado_id_rol_seq', 1, false);


--
-- Name: rol_id_rol_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.rol_id_rol_seq', 1, false);


--
-- Name: rol_permiso_id_rol_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.rol_permiso_id_rol_seq', 1, false);


--
-- Name: subcategoria_producto_id_subcategoria_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.subcategoria_producto_id_subcategoria_seq', 1, false);


--
-- Name: tipo_movimiento_caja_id_tipo_mov_caja_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.tipo_movimiento_caja_id_tipo_mov_caja_seq', 1, false);


--
-- Name: tipo_movimiento_id_tipo_movimiento_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.tipo_movimiento_id_tipo_movimiento_seq', 1, false);


--
-- Name: transferencia_informacion_id_transferencia_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.transferencia_informacion_id_transferencia_seq', 1, false);


--
-- Name: turno_id_turno_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.turno_id_turno_seq', 1, false);


--
-- Name: unidad_medida_id_unidad_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.unidad_medida_id_unidad_seq', 1, true);


--
-- Name: usuario_id_usuario_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.usuario_id_usuario_seq', 1, false);


--
-- Name: caja caja_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.caja
    ADD CONSTRAINT caja_pkey PRIMARY KEY (id_caja);


--
-- Name: categoria_producto categoria_producto_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.categoria_producto
    ADD CONSTRAINT categoria_producto_pkey PRIMARY KEY (id_categoria);


--
-- Name: ciudad ciudad_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.ciudad
    ADD CONSTRAINT ciudad_pkey PRIMARY KEY (id_ciudad);


--
-- Name: cliente cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (id_cliente);


--
-- Name: contacto_cliente contacto_cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.contacto_cliente
    ADD CONSTRAINT contacto_cliente_pkey PRIMARY KEY (id_contacto_cliente);


--
-- Name: contacto_proveedor contacto_proveedor_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.contacto_proveedor
    ADD CONSTRAINT contacto_proveedor_pkey PRIMARY KEY (id_contacto_proveedor);


--
-- Name: detalle_factura_compra detalle_factura_compra_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.detalle_factura_compra
    ADD CONSTRAINT detalle_factura_compra_pkey PRIMARY KEY (id_detalle_factura_compra);


--
-- Name: detalle_factura detalle_factura_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.detalle_factura
    ADD CONSTRAINT detalle_factura_pkey PRIMARY KEY (id_detalle_factura);


--
-- Name: detalle_inventario detalle_inventario_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.detalle_inventario
    ADD CONSTRAINT detalle_inventario_pkey PRIMARY KEY (id_detalle_inventario);


--
-- Name: detalle_orden_compra detalle_orden_compra_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.detalle_orden_compra
    ADD CONSTRAINT detalle_orden_compra_pkey PRIMARY KEY (id_detalle_orden_compra);


--
-- Name: detalle_pedido detalle_pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.detalle_pedido
    ADD CONSTRAINT detalle_pedido_pkey PRIMARY KEY (id_detalle_pedido);


--
-- Name: empleado empleado_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.empleado
    ADD CONSTRAINT empleado_pkey PRIMARY KEY (id_empleado);


--
-- Name: factura_compra factura_compra_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.factura_compra
    ADD CONSTRAINT factura_compra_pkey PRIMARY KEY (id_factura_compra);


--
-- Name: factura factura_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.factura
    ADD CONSTRAINT factura_pkey PRIMARY KEY (id_factura);


--
-- Name: forma_pago forma_pago_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.forma_pago
    ADD CONSTRAINT forma_pago_pkey PRIMARY KEY (id_forma_pago);


--
-- Name: historial_precio_producto historial_precio_producto_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.historial_precio_producto
    ADD CONSTRAINT historial_precio_producto_pkey PRIMARY KEY (id_historial_precio_producto);


--
-- Name: inventario inventario_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.inventario
    ADD CONSTRAINT inventario_pkey PRIMARY KEY (id_inventario);


--
-- Name: movimiento_caja movimiento_caja_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.movimiento_caja
    ADD CONSTRAINT movimiento_caja_pkey PRIMARY KEY (id_mov_caja);


--
-- Name: movimiento_inventario movimiento_inventario_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.movimiento_inventario
    ADD CONSTRAINT movimiento_inventario_pkey PRIMARY KEY (id_movimiento);


--
-- Name: orden_compra orden_compra_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.orden_compra
    ADD CONSTRAINT orden_compra_pkey PRIMARY KEY (id_orden_compra);


--
-- Name: pago_proveedor pago_proveedor_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.pago_proveedor
    ADD CONSTRAINT pago_proveedor_pkey PRIMARY KEY (id_pago);


--
-- Name: pais pais_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.pais
    ADD CONSTRAINT pais_pkey PRIMARY KEY (id_pais);


--
-- Name: pedido pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.pedido
    ADD CONSTRAINT pedido_pkey PRIMARY KEY (id_pedido);


--
-- Name: permiso permiso_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.permiso
    ADD CONSTRAINT permiso_pkey PRIMARY KEY (id_permiso);


--
-- Name: producto producto_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT producto_pkey PRIMARY KEY (id_producto);


--
-- Name: proveedor proveedor_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.proveedor
    ADD CONSTRAINT proveedor_pkey PRIMARY KEY (id_proveedor);


--
-- Name: rol_empleado rol_empleado_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.rol_empleado
    ADD CONSTRAINT rol_empleado_pkey PRIMARY KEY (id_rol);


--
-- Name: rol_permiso rol_permiso_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.rol_permiso
    ADD CONSTRAINT rol_permiso_pkey PRIMARY KEY (id_rol);


--
-- Name: rol rol_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT rol_pkey PRIMARY KEY (id_rol);


--
-- Name: subcategoria_producto subcategoria_producto_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.subcategoria_producto
    ADD CONSTRAINT subcategoria_producto_pkey PRIMARY KEY (id_subcategoria);


--
-- Name: tipo_movimiento_caja tipo_movimiento_caja_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.tipo_movimiento_caja
    ADD CONSTRAINT tipo_movimiento_caja_pkey PRIMARY KEY (id_tipo_mov_caja);


--
-- Name: tipo_movimiento tipo_movimiento_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.tipo_movimiento
    ADD CONSTRAINT tipo_movimiento_pkey PRIMARY KEY (id_tipo_movimiento);


--
-- Name: transferencia_informacion transferencia_informacion_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.transferencia_informacion
    ADD CONSTRAINT transferencia_informacion_pkey PRIMARY KEY (id_transferencia);


--
-- Name: turno turno_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.turno
    ADD CONSTRAINT turno_pkey PRIMARY KEY (id_turno);


--
-- Name: rol uk43kr6s7bts1wqfv43f7jd87kp; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT uk43kr6s7bts1wqfv43f7jd87kp UNIQUE (nombre);


--
-- Name: usuario uk863n1y3x0jalatoir4325ehal; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk863n1y3x0jalatoir4325ehal UNIQUE (username);


--
-- Name: permiso uknwe6lkk7x7sbw94xcmbwgvycu; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.permiso
    ADD CONSTRAINT uknwe6lkk7x7sbw94xcmbwgvycu UNIQUE (nombre);


--
-- Name: producto ukprg65xyo6blunyqxq80xaqhlo; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT ukprg65xyo6blunyqxq80xaqhlo UNIQUE (codigo_producto);


--
-- Name: unidad_medida unidad_medida_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.unidad_medida
    ADD CONSTRAINT unidad_medida_pkey PRIMARY KEY (id_unidad);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario);


--
-- Name: usuario_rol usuario_rol_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.usuario_rol
    ADD CONSTRAINT usuario_rol_pkey PRIMARY KEY (id_usuario, id_rol);


--
-- Name: detalle_factura_compra fk1lxqiyipo5lckh05803rb9l0v; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.detalle_factura_compra
    ADD CONSTRAINT fk1lxqiyipo5lckh05803rb9l0v FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto);


--
-- Name: factura_compra fk1vcex6riw9nnov5jje9b8wnjr; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.factura_compra
    ADD CONSTRAINT fk1vcex6riw9nnov5jje9b8wnjr FOREIGN KEY (id_proveedor) REFERENCES public.proveedor(id_proveedor);


--
-- Name: caja fk1yfvnv9pdanq5r2u2sknfn0as; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.caja
    ADD CONSTRAINT fk1yfvnv9pdanq5r2u2sknfn0as FOREIGN KEY (id_empleado) REFERENCES public.empleado(id_empleado);


--
-- Name: detalle_factura_compra fk2fnd14ep5ada0evxn25mxi1ko; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.detalle_factura_compra
    ADD CONSTRAINT fk2fnd14ep5ada0evxn25mxi1ko FOREIGN KEY (id_factura_compra) REFERENCES public.factura_compra(id_factura_compra);


--
-- Name: empleado fk32iir1s9ju6883156bp2n4b0x; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.empleado
    ADD CONSTRAINT fk32iir1s9ju6883156bp2n4b0x FOREIGN KEY (id_ciudad) REFERENCES public.ciudad(id_ciudad);


--
-- Name: usuario_rol fk3ftpt75ebughsiy5g03b11akt; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.usuario_rol
    ADD CONSTRAINT fk3ftpt75ebughsiy5g03b11akt FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario);


--
-- Name: producto fk3p043787h0xuxlysix3m276bt; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT fk3p043787h0xuxlysix3m276bt FOREIGN KEY (id_categoria) REFERENCES public.categoria_producto(id_categoria);


--
-- Name: producto fk40xg6hxacskw94ff60dw82r77; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT fk40xg6hxacskw94ff60dw82r77 FOREIGN KEY (id_unidad) REFERENCES public.unidad_medida(id_unidad);


--
-- Name: orden_compra fk61e8h7c7gw7dahyyixbf7ltho; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.orden_compra
    ADD CONSTRAINT fk61e8h7c7gw7dahyyixbf7ltho FOREIGN KEY (id_empleado) REFERENCES public.empleado(id_empleado);


--
-- Name: contacto_proveedor fk7jgh0fa8mvtmlcdhe8qtcvqrn; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.contacto_proveedor
    ADD CONSTRAINT fk7jgh0fa8mvtmlcdhe8qtcvqrn FOREIGN KEY (id_proveedor) REFERENCES public.proveedor(id_proveedor);


--
-- Name: detalle_pedido fk7n9hdifr08joboojejveby1vr; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.detalle_pedido
    ADD CONSTRAINT fk7n9hdifr08joboojejveby1vr FOREIGN KEY (id_pedido) REFERENCES public.pedido(id_pedido);


--
-- Name: detalle_inventario fk85huo6ft82eo2b2u7u9qopjfe; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.detalle_inventario
    ADD CONSTRAINT fk85huo6ft82eo2b2u7u9qopjfe FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto);


--
-- Name: subcategoria_producto fk86k8to0r8ecgq4ieo2tr1amkf; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.subcategoria_producto
    ADD CONSTRAINT fk86k8to0r8ecgq4ieo2tr1amkf FOREIGN KEY (id_categoria) REFERENCES public.categoria_producto(id_categoria);


--
-- Name: pedido fk9y4jnyp1hxqa386cnly0ay9uw; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.pedido
    ADD CONSTRAINT fk9y4jnyp1hxqa386cnly0ay9uw FOREIGN KEY (id_cliente) REFERENCES public.cliente(id_cliente);


--
-- Name: movimiento_inventario fkbjxhsg43krfbchjotdasekqi; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.movimiento_inventario
    ADD CONSTRAINT fkbjxhsg43krfbchjotdasekqi FOREIGN KEY (id_tipo_movimiento) REFERENCES public.tipo_movimiento(id_tipo_movimiento);


--
-- Name: detalle_factura fkbtcmmj5awxvxq2gj65kx1v7ly; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.detalle_factura
    ADD CONSTRAINT fkbtcmmj5awxvxq2gj65kx1v7ly FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto);


--
-- Name: detalle_orden_compra fkcnt8ik8ono53rnnqmo6fuhh0h; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.detalle_orden_compra
    ADD CONSTRAINT fkcnt8ik8ono53rnnqmo6fuhh0h FOREIGN KEY (id_orden_compra) REFERENCES public.orden_compra(id_orden_compra);


--
-- Name: cliente fkddv8tueu64g1r8qjt8bpeu5qv; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT fkddv8tueu64g1r8qjt8bpeu5qv FOREIGN KEY (nationality_id_pais) REFERENCES public.pais(id_pais);


--
-- Name: detalle_inventario fkf5xtgaoqmrglydwfiaae2wkuw; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.detalle_inventario
    ADD CONSTRAINT fkf5xtgaoqmrglydwfiaae2wkuw FOREIGN KEY (id_inventario) REFERENCES public.inventario(id_inventario);


--
-- Name: contacto_cliente fkf6faiqbvy36nka0vdmqkctg1l; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.contacto_cliente
    ADD CONSTRAINT fkf6faiqbvy36nka0vdmqkctg1l FOREIGN KEY (id_cliente) REFERENCES public.cliente(id_cliente);


--
-- Name: cliente fkgmoeiwcrhhxkicpiuldlmhn0x; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT fkgmoeiwcrhhxkicpiuldlmhn0x FOREIGN KEY (id_ciudad) REFERENCES public.ciudad(id_ciudad);


--
-- Name: ciudad fkh96uk5etvw529uc18kdjhvdq9; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.ciudad
    ADD CONSTRAINT fkh96uk5etvw529uc18kdjhvdq9 FOREIGN KEY (id_pais) REFERENCES public.pais(id_pais);


--
-- Name: detalle_factura fkhc4e7swi6aa3e6uom3bwm2x6x; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.detalle_factura
    ADD CONSTRAINT fkhc4e7swi6aa3e6uom3bwm2x6x FOREIGN KEY (id_factura) REFERENCES public.factura(id_factura);


--
-- Name: detalle_orden_compra fkhcx4m5eplu6q1lht0o4y0ht2f; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.detalle_orden_compra
    ADD CONSTRAINT fkhcx4m5eplu6q1lht0o4y0ht2f FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto);


--
-- Name: factura fkhf4qd2e07en591ymcp74t1ebj; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.factura
    ADD CONSTRAINT fkhf4qd2e07en591ymcp74t1ebj FOREIGN KEY (id_pedido) REFERENCES public.pedido(id_pedido);


--
-- Name: movimiento_caja fkhw08ftkmr79jqg9wsv7rrptqd; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.movimiento_caja
    ADD CONSTRAINT fkhw08ftkmr79jqg9wsv7rrptqd FOREIGN KEY (id_caja) REFERENCES public.caja(id_caja);


--
-- Name: turno fkhyyo0e4asmovio3x8jmma8vbi; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.turno
    ADD CONSTRAINT fkhyyo0e4asmovio3x8jmma8vbi FOREIGN KEY (id_empleado) REFERENCES public.empleado(id_empleado);


--
-- Name: movimiento_caja fkio4o2yhwk9ptlb0v020va45ng; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.movimiento_caja
    ADD CONSTRAINT fkio4o2yhwk9ptlb0v020va45ng FOREIGN KEY (id_tipo_mov_caja) REFERENCES public.tipo_movimiento_caja(id_tipo_mov_caja);


--
-- Name: detalle_pedido fkjfm9pk0w2eag8tx8lu6pbego6; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.detalle_pedido
    ADD CONSTRAINT fkjfm9pk0w2eag8tx8lu6pbego6 FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto);


--
-- Name: producto fkkinjnx6sxv6kf9s6i21ttfnfo; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT fkkinjnx6sxv6kf9s6i21ttfnfo FOREIGN KEY (id_proveedor) REFERENCES public.proveedor(id_proveedor);


--
-- Name: usuario_rol fkkxcv7htfnm9x1wkofnud0ewql; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.usuario_rol
    ADD CONSTRAINT fkkxcv7htfnm9x1wkofnud0ewql FOREIGN KEY (id_rol) REFERENCES public.rol(id_rol);


--
-- Name: inventario fkldr1ejc7iue77wr5qnsgaj7d2; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.inventario
    ADD CONSTRAINT fkldr1ejc7iue77wr5qnsgaj7d2 FOREIGN KEY (id_empleado) REFERENCES public.empleado(id_empleado);


--
-- Name: empleado fklftw457251pnh2wpiw8pn1md0; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.empleado
    ADD CONSTRAINT fklftw457251pnh2wpiw8pn1md0 FOREIGN KEY (id_rol) REFERENCES public.rol_empleado(id_rol);


--
-- Name: movimiento_inventario fklkde1yc6teblf62ro9slw9qdw; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.movimiento_inventario
    ADD CONSTRAINT fklkde1yc6teblf62ro9slw9qdw FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto);


--
-- Name: orden_compra fkpgp1ooe3wmycq29kdj6qydybp; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.orden_compra
    ADD CONSTRAINT fkpgp1ooe3wmycq29kdj6qydybp FOREIGN KEY (id_proveedor) REFERENCES public.proveedor(id_proveedor);


--
-- Name: pedido fkqbl4adl78gxdv0wbx3nq03awv; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.pedido
    ADD CONSTRAINT fkqbl4adl78gxdv0wbx3nq03awv FOREIGN KEY (id_empleado) REFERENCES public.empleado(id_empleado);


--
-- Name: rol_permiso fkrhxhgw05bdvokfrpppumlfh5d; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.rol_permiso
    ADD CONSTRAINT fkrhxhgw05bdvokfrpppumlfh5d FOREIGN KEY (id_permiso) REFERENCES public.permiso(id_permiso);


--
-- Name: factura fks1vkgwvkxrt5hrmt0c50auyug; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.factura
    ADD CONSTRAINT fks1vkgwvkxrt5hrmt0c50auyug FOREIGN KEY (id_cliente) REFERENCES public.cliente(id_cliente);


--
-- Name: pago_proveedor fkswair8x6qr20rbrqj9vdupa6d; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.pago_proveedor
    ADD CONSTRAINT fkswair8x6qr20rbrqj9vdupa6d FOREIGN KEY (id_proveedor) REFERENCES public.proveedor(id_proveedor);


--
-- Name: rol_permiso fksxc3d8lmtj7em6n8j0wl4jwco; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.rol_permiso
    ADD CONSTRAINT fksxc3d8lmtj7em6n8j0wl4jwco FOREIGN KEY (id_rol) REFERENCES public.rol(id_rol);


--
-- Name: historial_precio_producto fktekqwx5wfve7xmxln2ac43c25; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.historial_precio_producto
    ADD CONSTRAINT fktekqwx5wfve7xmxln2ac43c25 FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto);


--
-- PostgreSQL database dump complete
--

\unrestrict p3uPbWa9swtg9ugQW7AmtyEAavBcX1xWeg7nwJEBdpldn1NnudCOya58Sh8tSAW

