-- Docker ejecuta este archivo solo la primera vez que se crea el volumen de Postgres.
-- El esquema lo crea Spring Boot (ddl-auto=update). Tras el primer arranque de la app, cargá:
--   docker exec -i pos_postgres psql -U posuser -d posdb < database/seed-data.sql
--
-- Ver database/README.md
