CREATE SCHEMA IF NOT EXISTS public;

-- =========================
-- UBICACION
-- =========================

CREATE TABLE pais (
    id_pais BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE ciudad (
    id_ciudad BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    id_pais BIGINT REFERENCES pais(id_pais)
);

-- =========================
-- ROLES Y USUARIOS
-- =========================

CREATE TABLE rol (
    id_rol BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE
);

/*
Ejemplos:
- ADMIN
- CAJERO
*/

CREATE TABLE usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    nombre VARCHAR(100),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    id_rol BIGINT REFERENCES rol(id_rol)
);

-- =========================
-- EMPLEADOS
-- =========================

CREATE TABLE empleado (
    id_empleado BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100),
    documento VARCHAR(20) UNIQUE,
    telefono VARCHAR(30),
    id_ciudad BIGINT REFERENCES ciudad(id_ciudad),
    id_usuario BIGINT UNIQUE REFERENCES usuario(id_usuario)
);

-- =========================
-- CLIENTES
-- =========================

CREATE TABLE cliente (
    id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100),
    document_type VARCHAR(50),
    document_number VARCHAR(50) UNIQUE,
    phone VARCHAR(30),
    gender VARCHAR(20),
    date_birth DATE,
    nationality_id_pais BIGINT REFERENCES pais(id_pais),
    id_ciudad BIGINT REFERENCES ciudad(id_ciudad)
);

-- =========================
-- PROVEEDORES
-- =========================

CREATE TABLE proveedor (
    id_proveedor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE contacto_proveedor (
    id_contacto_proveedor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_contacto VARCHAR(100),
    telefono VARCHAR(50),
    email VARCHAR(100),
    id_proveedor BIGINT REFERENCES proveedor(id_proveedor)
);

-- =========================
-- PRODUCTOS
-- =========================

CREATE TABLE categoria_producto (
    id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE subcategoria_producto (
    id_subcategoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    id_categoria BIGINT NOT NULL REFERENCES categoria_producto(id_categoria),
    UNIQUE(nombre, id_categoria)
);

CREATE TABLE unidad_medida (
    id_unidad BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    abreviatura VARCHAR(10)
);

CREATE TABLE producto (
    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_producto VARCHAR(20) NOT NULL UNIQUE,
    nombre VARCHAR(150) NOT NULL,
    descripcion TEXT,
    precio NUMERIC(12,2) NOT NULL CHECK (precio >= 0),
    stock_actual NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (stock_actual >= 0),
    id_subcategoria BIGINT REFERENCES subcategoria_producto(id_subcategoria),
    id_unidad BIGINT REFERENCES unidad_medida(id_unidad)
);

CREATE TABLE producto_proveedor (
    id_producto_proveedor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto BIGINT NOT NULL REFERENCES producto(id_producto),
    id_proveedor BIGINT NOT NULL REFERENCES proveedor(id_proveedor),
    codigo_proveedor VARCHAR(100),
    precio_costo NUMERIC(12,2) CHECK (precio_costo >= 0),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE(id_producto, id_proveedor)
);

-- =========================
-- HISTORIAL DE PRECIOS
-- =========================

CREATE TABLE historial_precio_producto (
    id_historial_precio_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto BIGINT NOT NULL REFERENCES producto(id_producto),
    id_proveedor BIGINT REFERENCES proveedor(id_proveedor),
    fecha_cambio TIMESTAMP NOT NULL,
    precio_costo_anterior NUMERIC(12,2),
    precio_costo_nuevo NUMERIC(12,2),
    precio_anterior NUMERIC(12,2),
    precio_nuevo NUMERIC(12,2) NOT NULL,
    margen_anterior NUMERIC(12,2),
    margen_nuevo NUMERIC(12,2),
    usuario_responsable VARCHAR(100)
);

-- =========================
-- FORMAS DE PAGO
-- =========================

CREATE TABLE forma_pago (
    id_forma_pago BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(100) NOT NULL UNIQUE
);

/*
Ejemplos:
- CONTADO
- TRANSFERENCIA
*/

-- =========================
-- CAJA
-- =========================

CREATE TABLE caja (
    id_caja BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_apertura TIMESTAMP,
    fecha_cierre TIMESTAMP,
    monto_inicial NUMERIC(12,2) DEFAULT 0 CHECK (monto_inicial >= 0),
    monto_final NUMERIC(12,2) DEFAULT 0 CHECK (monto_final >= 0),
    estado VARCHAR(20) NOT NULL CHECK (estado IN ('ABIERTA', 'CERRADA')),
    id_empleado BIGINT REFERENCES empleado(id_empleado)
);

CREATE TABLE tipo_movimiento_caja (
    id_tipo_mov_caja BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE
);

/*
Ejemplos:
- INGRESO
- EGRESO
*/

CREATE TABLE movimiento_caja (
    id_mov_caja BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMP NOT NULL,
    monto NUMERIC(12,2) NOT NULL CHECK (monto >= 0),
    motivo TEXT,
    id_caja BIGINT REFERENCES caja(id_caja),
    id_tipo_mov_caja BIGINT REFERENCES tipo_movimiento_caja(id_tipo_mov_caja),
    id_forma_pago BIGINT REFERENCES forma_pago(id_forma_pago)
);

-- =========================
-- INVENTARIO
-- =========================

CREATE TABLE tipo_movimiento (
    id_tipo_movimiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion VARCHAR(200)
);

/*
Ejemplos:
- COMPRA
- VENTA
- AJUSTE
*/

CREATE TABLE movimiento_inventario (
    id_movimiento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMP NOT NULL,
    cantidad NUMERIC(12,2) NOT NULL,
    referencia TEXT,
    id_producto BIGINT REFERENCES producto(id_producto),
    id_tipo_movimiento BIGINT REFERENCES tipo_movimiento(id_tipo_movimiento)
);

CREATE TABLE inventario (
    id_inventario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    observaciones TEXT,
    ajuste_realizado BOOLEAN DEFAULT FALSE,
    id_empleado BIGINT REFERENCES empleado(id_empleado)
);

CREATE TABLE detalle_inventario (
    id_detalle_inventario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad_sistema NUMERIC(12,2),
    cantidad_fisica NUMERIC(12,2),
    diferencia NUMERIC(12,2),
    id_inventario BIGINT REFERENCES inventario(id_inventario),
    id_producto BIGINT REFERENCES producto(id_producto)
);

CREATE TABLE inventario_ajuste (
    id_ajuste BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_ajuste DATE NOT NULL,
    tipo_ajuste VARCHAR(80),
    estado VARCHAR(50) NOT NULL,
    stock_anterior NUMERIC(12,2),
    nuevo_stock NUMERIC(12,2) NOT NULL,
    diferencia NUMERIC(12,2),
    justificacion TEXT,
    autorizado_por VARCHAR(200),
    id_producto BIGINT NOT NULL REFERENCES producto(id_producto)
);

-- =========================
-- ORDENES DE COMPRA
-- =========================

/*
La orden de compra representa:
"pedir mercadería al proveedor"

Todavía NO aumenta stock.
*/

CREATE TABLE orden_compra (
    id_orden_compra BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_emision DATE NOT NULL,
    estado VARCHAR(50) NOT NULL,
    observaciones TEXT,
    id_empleado BIGINT NOT NULL REFERENCES empleado(id_empleado),
    id_proveedor BIGINT NOT NULL REFERENCES proveedor(id_proveedor)
);

CREATE TABLE detalle_orden_compra (
    id_detalle_orden_compra BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad NUMERIC(12,2) NOT NULL CHECK (cantidad > 0),
    precio_unitario NUMERIC(12,2) NOT NULL CHECK (precio_unitario >= 0),
    id_orden_compra BIGINT NOT NULL REFERENCES orden_compra(id_orden_compra),
    id_producto BIGINT NOT NULL REFERENCES producto(id_producto)
);

-- =========================
-- FACTURA COMPRA
-- =========================

/*
La factura compra representa:
"la mercadería ya llegó"

Aquí SÍ aumenta stock.
*/

CREATE TABLE factura_compra (
    id_factura_compra BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMP NOT NULL,
    total NUMERIC(12,2) CHECK (total >= 0),
    id_proveedor BIGINT REFERENCES proveedor(id_proveedor),
    id_forma_pago BIGINT REFERENCES forma_pago(id_forma_pago)
);

CREATE TABLE detalle_factura_compra (
    id_detalle_factura_compra BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad NUMERIC(12,2) NOT NULL CHECK (cantidad > 0),
    precio_unitario NUMERIC(12,2) NOT NULL CHECK (precio_unitario >= 0),
    id_factura_compra BIGINT REFERENCES factura_compra(id_factura_compra),
    id_producto BIGINT REFERENCES producto(id_producto)
);

-- =========================
-- VENTAS
-- =========================

/*
NO existe tabla pedido.

La venta es directa:
cliente -> factura
*/

CREATE TABLE factura (
    id_factura BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMP NOT NULL,
    nro_factura VARCHAR(50) NOT NULL UNIQUE,
    total NUMERIC(12,2) NOT NULL CHECK (total >= 0),
    id_cliente BIGINT REFERENCES cliente(id_cliente),
    id_forma_pago BIGINT REFERENCES forma_pago(id_forma_pago)
);

CREATE TABLE detalle_factura (
    id_detalle_factura BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad NUMERIC(12,2) NOT NULL CHECK (cantidad > 0),
    precio_unitario NUMERIC(12,2) NOT NULL CHECK (precio_unitario >= 0),
    id_factura BIGINT REFERENCES factura(id_factura),
    id_producto BIGINT REFERENCES producto(id_producto)
);

CREATE TABLE transferencia_pago (
    id_transferencia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    banco VARCHAR(100),
    numero_comprobante VARCHAR(100),
    titular VARCHAR(150),
    fecha_transferencia TIMESTAMP NOT NULL,
    monto NUMERIC(12,2) NOT NULL CHECK (monto >= 0),
    id_factura BIGINT REFERENCES factura(id_factura)
);
